# Generated by Django 3.2.8 on 2022-02-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_portal', '0004_auto_20220227_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post_title',
            field=models.CharField(default=None, max_length=255, verbose_name='заголовок '),
        ),
    ]
