# Generated by Django 3.2.8 on 2022-02-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_portal', '0005_comment_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_title',
            field=models.CharField(default='', max_length=255, verbose_name='заголовок '),
        ),
    ]
