# Generated by Django 3.2.8 on 2022-02-28 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_portal', '0006_alter_comment_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post_title',
        ),
    ]
