# Generated by Django 3.2.8 on 2022-03-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_portal', '0008_auto_20220301_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.FileField(default=None, upload_to='uploads'),
        ),
    ]
