# Generated by Django 3.2.8 on 2022-03-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_portal', '0009_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.FileField(blank=True, upload_to='uploads'),
        ),
    ]
